# Generated by Django 3.0.7 on 2020-06-18 18:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('inProgress', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('lastModifiedDate', models.DateTimeField(auto_now_add=True)),
                ('resume', models.CharField(blank='true', max_length=200, null=True)),
                ('post', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Publish'), ('R', 'Remove'), ('X', 'Default')], default='X', max_length=2)),
                ('image', models.ImageField(upload_to='')),
                ('nbView', models.IntegerField(default=0)),
                ('nbLike', models.IntegerField(default=0)),
                ('nbUnlike', models.IntegerField(default=0)),
                ('nbComment', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Case')),
            ],
        ),
    ]
