# Generated by Django 3.0.7 on 2020-06-28 01:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='resume',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
