# Generated by Django 2.2.10 on 2020-06-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200619_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank='true', max_length=200, null=True),
        ),
    ]
