# Generated by Django 3.0.6 on 2020-05-31 01:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(blank='true', max_length=200, null=True)),
                ('Prenom', models.CharField(blank='true', max_length=200, null=True)),
                ('Message', ckeditor.fields.RichTextField()),
                ('Sujet', models.CharField(default='Contact', max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Date_modification', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('is_treat', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
