# Generated by Django 3.0.7 on 2020-06-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Date_modification',
            new_name='date_modif',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Nom',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Prenom',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Sujet',
            new_name='subject',
        ),
    ]
