# Generated by Django 3.0.7 on 2020-06-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200508_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='addressseller',
        ),
        migrations.RemoveField(
            model_name='account',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_seller',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='shopname',
        ),
        migrations.RemoveField(
            model_name='account',
            name='telephone',
        ),
    ]
