# Generated by Django 3.0.6 on 2020-05-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('is_sale', models.BooleanField(default=True)),
                ('is_actif', models.BooleanField(default=True)),
            ],
        ),
    ]
