# Generated by Django 3.0.6 on 2020-05-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
