# Generated by Django 3.0.7 on 2020-06-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_auto_20200531_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='is_sale',
        ),
    ]
